✅ STEP 1: Collect Dataset (Reviews)
Option A (Easy for beginner ⭐)

👉 Don’t scrape (to save time), use sample data first

In [1]:
import requests
from bs4 import BeautifulSoup

url = "https://www.amazon.in/product-reviews/B0FGY54N5T"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.content, "html.parser")

print(soup.title)

<title dir="ltr">Amazon Sign-In</title>


In [2]:
from bs4 import BeautifulSoup

with open("page.html", "r", encoding="utf-8") as f:
    soup = BeautifulSoup(f, "html.parser")

print(soup.title)

<title>Amazon.in:Customer reviews: Youthnic Women&amp;#39;s Poly Rayon Printed Alia Cut Peplum Top | Top for Office | Women&amp;#39;s Tunics | Short Kurti Women| Regular Fit</title>


In [4]:
from bs4 import BeautifulSoup

with open("page.html", "r", encoding="utf-8") as f:
    soup = BeautifulSoup(f, "html.parser")

reviews = soup.find_all("span", {"data-hook": "review-body"})

review_list = []

for r in reviews:
    # print(r)
    # print("---------------------------------------")
    review_list.append(r.text.strip())

print(review_list)
print(len(review_list))

['The quality is amazingg !!! The fabric is pure cotton, so very well for summer and the fitting is greatttt……. Great for everyday wear.', "It's very good.. Worth the price..", 'Beautiful ethnic top, great qualityI really loved this women’s cotton blend bandhani print peplum top❤️', 'Nice dress', 'Ok,', 'The product was received by me without any tag ... The same when returned due to size difficulty the Person said there is no tag ... But none was received ... This is very disappointing never happened with me ... Least expected', 'Beautiful - love the shade! It looks great on jeans! Palazzo or dhoti!', 'Not so good', "It's good", 'Great purchase. I like both the material and fittings.Go for it girls']
10


In [5]:
# STEP 1: Lowercase
review_list = [r.lower() for r in review_list]

print(review_list)

['the quality is amazingg !!! the fabric is pure cotton, so very well for summer and the fitting is greatttt……. great for everyday wear.', "it's very good.. worth the price..", 'beautiful ethnic top, great qualityi really loved this women’s cotton blend bandhani print peplum top❤️', 'nice dress', 'ok,', 'the product was received by me without any tag ... the same when returned due to size difficulty the person said there is no tag ... but none was received ... this is very disappointing never happened with me ... least expected', 'beautiful - love the shade! it looks great on jeans! palazzo or dhoti!', 'not so good', "it's good", 'great purchase. i like both the material and fittings.go for it girls']


In [6]:
# STEP 2: Remove punctuation
import re

def remove_punctuation(text):
    return re.sub(r'[^\w\s]', '', text)

review_list = [remove_punctuation(r) for r in review_list]

print(review_list)

['the quality is amazingg  the fabric is pure cotton so very well for summer and the fitting is greatttt great for everyday wear', 'its very good worth the price', 'beautiful ethnic top great qualityi really loved this womens cotton blend bandhani print peplum top', 'nice dress', 'ok', 'the product was received by me without any tag  the same when returned due to size difficulty the person said there is no tag  but none was received  this is very disappointing never happened with me  least expected', 'beautiful  love the shade it looks great on jeans palazzo or dhoti', 'not so good', 'its good', 'great purchase i like both the material and fittingsgo for it girls']


In [7]:
# STEP 3: Tokenization
tokens_list = [r.split() for r in review_list]

print(tokens_list)

[['the', 'quality', 'is', 'amazingg', 'the', 'fabric', 'is', 'pure', 'cotton', 'so', 'very', 'well', 'for', 'summer', 'and', 'the', 'fitting', 'is', 'greatttt', 'great', 'for', 'everyday', 'wear'], ['its', 'very', 'good', 'worth', 'the', 'price'], ['beautiful', 'ethnic', 'top', 'great', 'qualityi', 'really', 'loved', 'this', 'womens', 'cotton', 'blend', 'bandhani', 'print', 'peplum', 'top'], ['nice', 'dress'], ['ok'], ['the', 'product', 'was', 'received', 'by', 'me', 'without', 'any', 'tag', 'the', 'same', 'when', 'returned', 'due', 'to', 'size', 'difficulty', 'the', 'person', 'said', 'there', 'is', 'no', 'tag', 'but', 'none', 'was', 'received', 'this', 'is', 'very', 'disappointing', 'never', 'happened', 'with', 'me', 'least', 'expected'], ['beautiful', 'love', 'the', 'shade', 'it', 'looks', 'great', 'on', 'jeans', 'palazzo', 'or', 'dhoti'], ['not', 'so', 'good'], ['its', 'good'], ['great', 'purchase', 'i', 'like', 'both', 'the', 'material', 'and', 'fittingsgo', 'for', 'it', 'girls']]


In [8]:
# STEP 4: Remove Stopwords (Optional but good)
from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

tokens_list = [
    [word for word in tokens if word not in stop_words]
    for tokens in tokens_list
]

print(tokens_list)

[['quality', 'amazingg', 'fabric', 'pure', 'cotton', 'well', 'summer', 'fitting', 'greatttt', 'great', 'everyday', 'wear'], ['good', 'worth', 'price'], ['beautiful', 'ethnic', 'top', 'great', 'qualityi', 'really', 'loved', 'womens', 'cotton', 'blend', 'bandhani', 'print', 'peplum', 'top'], ['nice', 'dress'], ['ok'], ['product', 'received', 'without', 'tag', 'returned', 'due', 'size', 'difficulty', 'person', 'said', 'tag', 'none', 'received', 'disappointing', 'never', 'happened', 'least', 'expected'], ['beautiful', 'love', 'shade', 'looks', 'great', 'jeans', 'palazzo', 'dhoti'], ['good'], ['good'], ['great', 'purchase', 'like', 'material', 'fittingsgo', 'girls']]


[nltk_data] Downloading package stopwords to C:\Users\Shraddha
[nltk_data]     Chaudhari\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


TASK 2: Vocabulary Creation (VERY EASY)
🧠 What is Vocabulary?

👉 Vocabulary = all unique words from your data

🔍 Example

If your cleaned data is:

[
 ['quality', 'amazing'],
 ['good'],
 ['nice', 'dress']
]

👉 Vocabulary becomes:

['quality', 'amazing', 'good', 'nice', 'dress']

👉 No duplicates ❗


In [16]:
tokens_list = [
    ['good', 'product'],
    ['good', 'quality'],
    ['bad', 'product']
]

In [17]:
from collections import Counter

all_words = []

for tokens in tokens_list:
    all_words.extend(tokens)
    # print(tokens)
    # print(all_words)
    
print("----------------------------------------")
vocab = Counter(all_words)

print("Vocabulary:", vocab)
print("Vocabulary size:", len(vocab))
print("Top 5 words:", vocab.most_common(5))

----------------------------------------
Vocabulary: Counter({'good': 2, 'product': 2, 'quality': 1, 'bad': 1})
Vocabulary size: 4
Top 5 words: [('good', 2), ('product', 2), ('quality', 1), ('bad', 1)]


Make Vocabulary

In [ ]:
# TASK 3: Feature Engineering
# Now we convert words → numbers

# 🔹 1. One Hot Encoding (Simple)

# 👉 Idea:

# If word present → 1
# If not → 0

# Convert to list
vocab_list = list(vocab.keys())
print("Vocabulary List:(Unique words)", vocab_list)

# Output:
# ['good', 'product', 'quality', 'bad']

def one_hot(doc):
    return [1 if word in doc else 0 for word in vocab_list]

ohe_vectors = [one_hot(doc) for doc in tokens_list]

print(ohe_vectors)

# Output
# [
#  [1, 1, 0, 0],   # good product
#  [1, 0, 1, 0],   # good quality
#  [0, 1, 0, 1]    # bad product
# ]

Vocabulary List:(Unique words) ['good', 'product', 'quality', 'bad']
[[1, 1, 0, 0], [1, 0, 1, 0], [0, 1, 0, 1]]


In [13]:
review_list1 = [
    "good product",
    "good quality",
    "bad product"
]

🔹 1. One Hot Encoding (OHE)
🧠 Idea:

👉 Only checks word present or not (0 or 1)

In [ ]:
# # Step 1: create vocabulary
# vocab = set()
# for sentence in review_list1:
#     for word in sentence.split():
#         vocab.add(word)

# vocab = list(vocab)
# print("Vocabulary:", vocab)

# # Step 2: OHE function
# def one_hot(sentence):
#     words = sentence.split()
#     return [1 if word in words else 0 for word in vocab]

# # Step 3: Apply
# ohe_vectors = [one_hot(sentence) for sentence in review_list1]

# print("OHE:", ohe_vectors)

Vocabulary: ['quality', 'product', 'good', 'bad']
OHE: [[0, 1, 1, 0], [1, 0, 1, 0], [0, 1, 0, 1]]


2. Bag of Words (BoW)

Now use original text (not tokens)

review_list1 = [
    "good product",
    "good quality",
    "bad product"
]

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

bow = cv.fit_transform(review_list1)

print(cv.get_feature_names_out())
print(bow.toarray())

['bad' 'good' 'product' 'quality']
[[0 1 1 0]
 [0 1 0 1]
 [1 0 1 0]]


Output

Words:

['bad', 'good', 'product', 'quality']

Matrix:

[
 [0, 1, 1, 0],   # good product
 [0, 1, 0, 1],   # good quality
 [1, 0, 1, 0]    # bad product
]

---------------------------------------------------

 Points:
 
 Difference from OHE

 Looks same here 
 Because words appear only once

 If repeated word:
review_list = ["good good product"]

 Output:

[0, 2, 1, 0]

 Now:

good → 2
product → 1

✔ This is frequency

3. TF-IDF

 Same data:

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(review_list1)

print(tfidf.get_feature_names_out())
print(tfidf_matrix.toarray())

['bad' 'good' 'product' 'quality']
[[0.         0.70710678 0.70710678 0.        ]
 [0.         0.60534851 0.         0.79596054]
 [0.79596054 0.         0.60534851 0.        ]]


 Meaning

 Values are:

NOT count ❌
NOT 0/1 ❌
They are importance score

 Simple Comparison
 
Method	Output	Meaning
OHE	    0 / 1	present or not
BoW	    0,1,2…	count
TF-IDF	decimal	importance

Very Simple Example Summary

Sentence:

"good good product"

| Method | Output     |
| ------ | ---------- |
| OHE    | [1,1]      |
| BoW    | [2,1]      |
| TF-IDF | [0.6, 0.4] |

Final Understanding

 OHE → simple (only presence)
 BoW → better (counts)
 TF-IDF → best (importance)

 TASK 4: Comparison Analysis
1. Comparison Table

| Feature        | OHE (One Hot Encoding) | BoW (Bag of Words) | TF-IDF           |
| -------------- | ---------------------- | ------------------ | ---------------- |
| Value          | 0 or 1                 | Count (0,1,2…)     | Decimal (weight) |
| Meaning        | Word present or not    | Word frequency     | Word importance  |
| Repeated words | Not counted            | Counted            | Weighted         |
| Common words   | Same importance        | Same importance    | Low importance   |
| Rare words     | Same importance        | Same importance    | High importance  |
| Use case       | Simple models          | Basic NLP          | Advanced NLP     |


 2. Which words are most important in TF-IDF?

 Rare words are most important 

 Example
good product
good quality
bad product

Word count:

| Word    | Frequency |
| ------- | --------- |
| good    | 2         |
| product | 2         |
| bad     | 1         |
| quality | 1         |

 So:

bad, quality → HIGH importance 
good, product → LOW importance 

 3. Why common words get LOW weight?

 Because:

They appear in many sentences
They are NOT special
 Simple Explanation (write this)

“In TF-IDF, rare words are more important because they appear in fewer documents and carry more meaningful information. Common words appear in many documents, so their importance is reduced.”

TASK 5: Sparse Matrix Analysis
1. Print Shape of Matrix


In [23]:
print(bow.shape)
print(tfidf_matrix.shape)

(3, 4)
(3, 4)


Meaning:

3 rows → 3 sentences
4 columns → 4 words

2. Calculate Sparsity (% of zeros)
Code:

In [25]:
import numpy as np

matrix = bow.toarray()   # or tfidf_matrix.toarray()

zero_count = np.sum(matrix == 0)
total_elements = matrix.size

sparsity = (zero_count / total_elements) * 100
print("Zero count:", zero_count)
print("Total elements:", total_elements)
print("Sparsity:", sparsity, "%")

Zero count: 6
Total elements: 12
Sparsity: 50.0 %


🔍 Example

Matrix:

[
 [0,1,1,0],
 [0,1,0,1],
 [1,0,1,0]
]

👉 Total elements = 12
👉 Zero count = 6

👉 Sparsity:

50%
🧠 What is Sparsity?

👉 Percentage of zero values in matrix

🔹 3. Why sparse matrices are inefficient?

👉 ❌ When converted to dense (.toarray()):

Problems:
Uses more memory
Slower processing
Large data becomes difficult
🎯 Simple Answer (write this)

“Sparse matrices are inefficient when converted to dense format because they contain many zero values, which increases memory usage and computation time in large-scale systems.”

✅ 🧠 Task 6: Real-world Questions
🔹 1. Why Bag of Words fails in understanding semantic meaning?

👉 Main idea:
BoW only counts words, it does NOT understand meaning ❌

🔍 Example
Sentence 1: "This product is good"
Sentence 2: "This product is excellent"

👉 Meaning:

good ≈ excellent (same meaning)

👉 But BoW treats them as:

different words ❗

So:

good ≠ excellent

👉 Model thinks they are unrelated ❌

🔍 Another example
"I love this product"
"I hate this product"

👉 BoW:

both have similar words
👉 Cannot understand opposite meaning ❌
🎯 Final Answer (write this)

“Bag of Words fails to capture semantic meaning because it treats each word independently and does not understand relationships between words. Similar words like ‘good’ and ‘excellent’ are treated as different, and it also cannot capture context or sentiment.”

🔹 2. When to use BoW and TF-IDF in industry?
✅ Use Bag of Words when:
Simple text classification
Small dataset
Fast implementation needed

👉 Examples:

Spam detection
Basic sentiment analysis
✅ Use TF-IDF when:
Need better importance of words
Want to ignore common words
Medium-level NLP tasks

👉 Examples:

Search engines
Document similarity
Review analysis

🎯 Final Answer (write this)

“Bag of Words is used in simple applications like spam detection and basic classification where speed is important. TF-IDF is used when we need better feature representation, such as in search engines, document ranking, and sentiment analysis.”

Question🔹 3. Limitations of TF-IDF in real applications
❌ 1. No semantic meaning

👉 Same problem as BoW

good ≠ excellent
❌ 2. Ignores word order
"not good" → treated similar to "good"

👉 Meaning lost ❌

❌ 3. Cannot understand context

👉 Example:

"Apple is a fruit"
"Apple is a company"

👉 TF-IDF cannot differentiate ❌

❌ 4. High dimensional data

👉 Many words → large vectors
👉 Memory + computation issue

🎯 Final Answer (write this)

“TF-IDF has limitations such as lack of semantic understanding, ignoring word order, inability to capture context, and high dimensionality. It cannot understand relationships between words and may not perform well in complex NLP tasks.”

🎯 FINAL SUMMARY
Question	Key Idea
BoW limitation	No meaning
Use cases	BoW (simple), TF-IDF (better)
TF-IDF limits	No context, no order

TASK 7: Sentiment Classification

👉 Goal:

Input: review text
Output: positive (1) or negative (0)

🌱 Step 1: Create Simple Dataset

👉 Use small data first (easy to understand)

In [27]:
review_list2 = [
    "good product",
    "excellent quality",
    "bad product",
    "very poor quality",
    "nice item",
    "waste of money"
]

labels = [1, 1, 0, 0, 1, 0]   # 1 = positive, 0 = negative

Step 2: Train-Test Split

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    review_list2, labels, test_size=0.3, random_state=42
)

Step 3: Bag of Words Mod

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

# Convert text → numbers
cv = CountVectorizer()
X_train_bow = cv.fit_transform(X_train)
X_test_bow = cv.transform(X_test)

# Train model
model_bow = LogisticRegression()
model_bow.fit(X_train_bow, y_train)

# Accuracy
accuracy_bow = model_bow.score(X_test_bow, y_test)
print("BoW Accuracy:", accuracy_bow)

BoW Accuracy: 0.0


Step 4: TF-IDF Model

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

model_tfidf = LogisticRegression()
model_tfidf.fit(X_train_tfidf, y_train)

accuracy_tfidf = model_tfidf.score(X_test_tfidf, y_test)
print("TF-IDF Accuracy:", accuracy_tfidf)

TF-IDF Accuracy: 0.0


📊 Step 5: Compare Results

👉 Output example:

BoW Accuracy: 0.66
TF-IDF Accuracy: 0.83
🧠 Meaning

👉 TF-IDF usually better because:

Focuses on important words
Ignores common words
🎯 Final Comparison (Write this)
Method	Accuracy	Reason
BoW	Lower	treats all words equally
TF-IDF	Higher	gives importance to useful words
🧠 Simple Explanation

👉 BoW:

Counts words
Does not know importance

👉 TF-IDF:

Finds important words
Better for prediction
🎯 Final Answer (Write in assignment)

“In this task, sentiment classification was performed using Logistic Regression. The model was trained using both Bag of Words and TF-IDF features. TF-IDF performed better than BoW because it assigns higher importance to meaningful words and reduces the weight of common words.”

🚀 BONUS (Optional: Try Naive Bayes)
from sklearn.naive_bayes import MultinomialNB

model_nb = MultinomialNB()
model_nb.fit(X_train_tfidf, y_train)

print("Naive Bayes Accuracy:", model_nb.score(X_test_tfidf, y_test))

In [32]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

print("Accuracy:", model.score(X_test_tfidf, y_test))

Accuracy: 0.0
